In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Everything is ready!")
print("pandas version:", pd.__version__)

Everything is ready!
pandas version: 3.1.0

In [3]:
product = "Laptop"
price = 850
quantity = 3
discount = 0.10

In [6]:
revenue_before_discount = price * quantity
discount_amount = revenue_before_discount * discount
final_revenue = revenue_before_discount - discount_amount

print("Product:", product)
print("Revenue before discount:", revenue_before_discount)
print("Discount:", discount_amount)
print("Final revenue:", final_revenue)

Product: Laptop
Revenue before discount: 2550
Discount: 255.0
Final revenue: 2295.0

In [7]:
print(type(product))
print(type(price))
print(type(quantity))
print(type(discount))

<class 'str'>
<class 'int'>
<class 'int'>
<class 'float'>

In [8]:
Product = "Laptop"
Price = 240
Quantity = 5
Discount = 0.15

In [9]:
Revenue_before_discount = Price * Quantity
Discount_amount = Revenue_before_discount * Discount
Final_revenue = Revenue_before_discount - Discount_amount
print("Product:", Product)
print("Revenue before discount:", Revenue_before_discount)
print("Discount:", Discount_amount)
print("Final revenue:", Final_revenue)

Product: Laptop
Revenue before discount: 1200
Discount: 180.0
Final revenue: 1020.0

In [10]:
daily_sales = [120, 95, 150, 80, 200, 175, 110]
print(daily_sales)

[120, 95, 150, 80, 200, 175, 110]

In [11]:
print("Monday:", daily_sales[0])
print("Tuesday:", daily_sales[1])
print("Sunday:", daily_sales[6])
print("Last day:", daily_sales[-1])

Monday: 120
Tuesday: 95
Sunday: 110
Last day: 110

In [12]:
total_sales = sum(daily_sales)
number_of_days = len(daily_sales)
average_sales = total_sales / number_of_days
highest_sales = max(daily_sales)
lowest_sales = min(daily_sales)

print("Total sales:", total_sales)
print("Average:", average_sales)
print("Highest sales:", highest_sales)
print("Lowest sales:", lowest_sales)

Total sales: 930
Average: 132.85714285714286
Highest sales: 200
Lowest sales: 80

In [13]:
print("Average:", round(average_sales, 2))

Average: 132.86

In [14]:
sales = [350, 420, 280, 510, 390]

In [17]:
total_sales = sum(sales)
average_sales = total_sales / len(sales)
highest_sales = max(sales)
lowest_sales = min(sales)

print("Total sales:", total_sales)
print("Average sales:", round(average_sales, 2))
print("Highest sales:", highest_sales)
print("Lowest sales:", lowest_sales)
print("The first sale:", sales[0])
print("The last sale:", sales[-1])

Total sales: 1950
Average sales: 390.0
Highest sales: 510
Lowest sales: 280
The first sale: 350
The last sale: 390

In [18]:
print(sales)

[350, 420, 280, 510, 390]

In [19]:
sales = [350, 420, 280, 510, 390]
target = 400

for sale in sales:
    if sale > target:
        print(sale, "is above target")
    else:
        print(sale, "is not above target")

350 is not above target
420 is above target
280 is not above target
510 is above target
390 is not above target

In [21]:
profits = [120, -30, 75, -15, 200, 0, 95]
target = 0
profitable_count = 0
loss_count = 0
break_even_count = 0
for profit in profits:
    if profit > target:
        print(profit, "is profitable")
        profitable_count += 1
    elif profit < target:
        print(profit, "is a loss")
        loss_count += 1
    else:
        print(profit, "is break-even")
        break_even_count += 1

print("Profitable days:", profitable_count)
print("Loss days:", loss_count)
print("Break-even days:", break_even_count)

120 is profitable
-30 is a loss
75 is profitable
-15 is a loss
200 is profitable
0 is break-even
95 is profitable
Profitable days: 4
Loss days: 2
Break-even days: 1

In [22]:
# we use def to make a function, that can save us time
def calculate_average(values):
    total = sum(values)
    average = total / len(values)
    return average

sales_week_1 = [350, 420, 280, 510, 390]
sales_week_2 = [440, 380, 525, 475, 600]

print("Average sales for week 1:", calculate_average(sales_week_1))
print("Average sales for week 2:", calculate_average(sales_week_2))

Average sales for week 1: 390.0
Average sales for week 2: 484.0

In [23]:
def percentage_change(old_value, new_value):
    change = new_value - old_value
    percentage = (change / old_value) * 100
    return percentage

last_year_sales = 40000
this_year_sales = 46000
print("Percentage sale change", percentage_change(last_year_sales, this_year_sales))

Percentage sale change 15.0

In [25]:
def percentage_change(old_value, new_value):
    change = new_value - old_value
    percentage = (change / old_value) * 100
    return percentage

first_value = 500
second_value = 425

print("Percentage change:", percentage_change(first_value, second_value), "%")

Percentage change: -15.0 %

In [26]:
import pandas as pd

data = {
    "product": ["Laptop", "Monitor", "Keyboard", "Mouse"],
    "price": [850, 240, 75, 35],
    "quantity": [3, 5, 10, 20]
}

df = pd.DataFrame(data)
df

    product  price  quantity
0    Laptop    850         3
1   Monitor    240         5
2  Keyboard     75        10
3     Mouse     35        20

In [27]:
df["revenue"] = df["price"] * df["quantity"]
df

    product  price  quantity  revenue
0    Laptop    850         3     2550
1   Monitor    240         5     1200
2  Keyboard     75        10      750
3     Mouse     35        20      700

In [28]:
print("Total revenue:", df["revenue"].sum())
print("Average price:", df["price"].mean())
print("Most expensive:", df["price"].max())

Total revenue: 5200
Average price: 300.0
Most expensive: 850

In [29]:
expensive_product = df[df["price"] > 100]
expensive_product

   product  price  quantity  revenue
0   Laptop    850         3     2550
1  Monitor    240         5     1200

In [30]:
df["price_with_tax"] = df["price"] * 1.20

In [31]:
df

    product  price  quantity  revenue  price_with_tax
0    Laptop    850         3     2550          1020.0
1   Monitor    240         5     1200           288.0
2  Keyboard     75        10      750            90.0
3     Mouse     35        20      700            42.0

In [35]:
highest_revenue_product = df.loc[df["revenue"].idxmax()]
print(highest_revenue_product)

product             Laptop
price                  850
quantity                 3
revenue               2550
price_with_tax      1020.0
revenue_with_tax    3060.0
Name: 0, dtype: object

In [36]:
df["revenue_with_tax"] = df["price_with_tax"] * df["quantity"]
df

    product  price  quantity  revenue  price_with_tax  revenue_with_tax
0    Laptop    850         3     2550          1020.0            3060.0
1   Monitor    240         5     1200           288.0            1440.0
2  Keyboard     75        10      750            90.0             900.0
3     Mouse     35        20      700            42.0             840.0

In [37]:
df.loc[df["revenue_with_tax"].idxmax()]

product             Laptop
price                  850
quantity                 3
revenue               2550
price_with_tax      1020.0
revenue_with_tax    3060.0
Name: 0, dtype: object

In [38]:
highest = df.loc[
    df["revenue_with_tax"].idxmax(),
    ["product", "revenue", "revenue_with_tax"]
]

print(highest)

product             Laptop
revenue               2550
revenue_with_tax    3060.0
Name: 0, dtype: object