In [ ]:
product_name = "Tablet"
Price = 320
Quantity = 7
Discount = 0.12

Revenue_before_discount = Price * Quantity
Discount_amount = Revenue_before_discount * Discount
Final_revenue = Revenue_before_discount - Discount_amount

print("Revenue before discount:", Revenue_before_discount, "EUR")
print("Discount amount:", Discount_amount, "EUR")
print("Final revenue:", Final_revenue, "EUR")

print("Tablet type:", type(product_name))
print("Price type:", type(Price))
print("Quantity type:", type(Quantity))
print("Discount type:", type(Discount))

Revenue before discount: 2240 EUR
Discount amount: 268.8 EUR
Final revenue: 1971.2 EUR
Tablet type: <class 'str'>
Price type: <class 'int'>
Quantity type: <class 'int'>
Discount type: <class 'float'>
Final revenue: {final_revenue:.2f} EUR

In [6]:
daily_sales = [450, 520, 390, 610, 480, 700, 550]

total_sales = sum(daily_sales)
print("Total sales:", total_sales)
average_sales = total_sales / len(daily_sales)
print("Average daily sales:", round(average_sales, 2))
highest_sale = max(daily_sales)
print("Highest daily sale:", highest_sale)
lowest_sale = min(daily_sales)
print("Lowest daily sale:", lowest_sale)
first_sale = daily_sales[0]
print("First daily sale:", first_sale)
last_sale = daily_sales[-1]
print("Last daily sale:", last_sale)
diff_high_low = highest_sale - lowest_sale
print("Difference between highest and lowest daily sales:", diff_high_low)

Total sales: 3700
Average daily sales: 528.57
Highest daily sale: 700
Lowest daily sale: 390
First daily sale: 450
Last daily sale: 550
Difference between highest and lowest daily sales: 310

In [8]:
# task 3

daily_sales = [450, 520, 390, 610, 480, 700, 550]
target = 500
above_target = 0
below_target = 0
on_target = 0
for sale in daily_sales:
    if sale > target:
        print(sale, "is above the target of", target)
        above_target += 1
    elif sale == target:
        print(sale, "is equal to the target of", target)
        on_target += 1
    else:
        print(sale, "is below the target of", target)
        below_target += 1

print("Number of sales above target:", above_target)
print("Number of sales below target:", below_target)
print("Number of sales on target:", on_target)

450 is below the target of 500
520 is above the target of 500
390 is below the target of 500
610 is above the target of 500
480 is below the target of 500
700 is above the target of 500
550 is above the target of 500
Number of sales above target: 4
Number of sales below target: 3
Number of sales on target: 0

In [11]:
# part 4. funcions. def
#percentage change function

def percentage_change(new_value, old_value):
    if old_value == 0:
        return "Old value cannot be zero for percentage change calculation."
    change = new_value - old_value
    percent_change = (change / old_value) * 100
    return percent_change

first_old = 12000
first_new = 15000
second_old = 8000
second_new = 6800
third_old = 500
third_new = 500
print("Percentage change from", first_old, "to", first_new, "is:", percentage_change(first_new, first_old), "%")
print("Percentage change from", second_old, "to", second_new, "is:", percentage_change(second_new, second_old), "%")
print("Percentage change from", third_old, "to", third_new, "is:", percentage_change(third_new, third_old), "%")

Percentage change from 12000 to 15000 is: 25.0 %
Percentage change from 8000 to 6800 is: -15.0 %
Percentage change from 500 to 500 is: 0.0 %

In [15]:
import pandas as pd

data = {
    "product": [
        "Laptop",
        "Monitor",
        "Keyboard",
        "Mouse",
        "Headphones",
        "Webcam"
    ],
    "category": [
        "Computers",
        "Displays",
        "Accessories",
        "Accessories",
        "Audio",
        "Accessories"
    ],
    "price": [850, 240, 75, 35, 120, 95],
    "quantity": [3, 5, 10, 20, 8, 6]
}

df = pd.DataFrame(data)
df

      product     category  price  quantity
0      Laptop    Computers    850         3
1     Monitor     Displays    240         5
2    Keyboard  Accessories     75        10
3       Mouse  Accessories     35        20
4  Headphones        Audio    120         8
5      Webcam  Accessories     95         6

KeyError: slice(0, 3, None)

In [30]:
df = pd.DataFrame(data)
df[["product", "category", "price"]]

      product     category  price
0      Laptop    Computers    850
1     Monitor     Displays    240
2    Keyboard  Accessories     75
3       Mouse  Accessories     35
4  Headphones        Audio    120
5      Webcam  Accessories     95

In [31]:
print("Shape:", df.shape)
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Column names:", list(df.columns))

Shape: (6, 4)
Rows: 6
Columns: 4
Column names: ['product', 'category', 'price', 'quantity']

In [34]:
df["revenue"] = df["price"] * df["quantity"]

In [35]:
df

      product     category  price  quantity  revenue
0      Laptop    Computers    850         3     2550
1     Monitor     Displays    240         5     1200
2    Keyboard  Accessories     75        10      750
3       Mouse  Accessories     35        20      700
4  Headphones        Audio    120         8      960
5      Webcam  Accessories     95         6      570

In [36]:
df["tax"] = df["price"] * 0.2
df["price_with_tax"] = df["price"]*1.20
df["revenue_with_tax"] = df["price_with_tax"] * df["quantity"]

df

,product,category,price,quantity,revenue,tax,price_with_tax,revenue_with_tax
0,Laptop,Computers,850,3,2550,170.0,1020.0,3060.0
1,Monitor,Displays,240,5,1200,48.0,288.0,1440.0
2,Keyboard,Accessories,75,10,750,15.0,90.0,900.0
3,Mouse,Accessories,35,20,700,7.0,42.0,840.0
4,Headphones,Audio,120,8,960,24.0,144.0,1152.0
5,Webcam,Accessories,95,6,570,19.0,114.0,684.0

In [38]:
total_revenue = df["revenue"].sum()
total_revenue_with_tax = df["revenue_with_tax"].sum()

print("Total revenue:", total_revenue, "EUR")
print("Total revenue with tax:", total_revenue_with_tax, "EUR")

Total revenue: 6730 EUR
Total revenue with tax: 8076.0 EUR

In [39]:
print("Final shape:", df.shape)

Final shape: (6, 8)

In [40]:
expensive_products = df[df["price"] > 100]
expensive_products

,product,category,price,quantity,revenue,tax,price_with_tax,revenue_with_tax
0,Laptop,Computers,850,3,2550,170.0,1020.0,3060.0
1,Monitor,Displays,240,5,1200,48.0,288.0,1440.0
4,Headphones,Audio,120,8,960,24.0,144.0,1152.0

In [41]:
high_revenue_products = df[df["revenue"] > 1000]
high_revenue_products

,product,category,price,quantity,revenue,tax,price_with_tax,revenue_with_tax
0,Laptop,Computers,850,3,2550,170.0,1020.0,3060.0
1,Monitor,Displays,240,5,1200,48.0,288.0,1440.0

In [42]:
df[df["quantity"] >= 8]

,product,category,price,quantity,revenue,tax,price_with_tax,revenue_with_tax
2,Keyboard,Accessories,75,10,750,15.0,90.0,900.0
3,Mouse,Accessories,35,20,700,7.0,42.0,840.0
4,Headphones,Audio,120,8,960,24.0,144.0,1152.0

In [43]:
accessories = df[df["category"] == "Accessories"]
accessories

,product,category,price,quantity,revenue,tax,price_with_tax,revenue_with_tax
2,Keyboard,Accessories,75,10,750,15.0,90.0,900.0
3,Mouse,Accessories,35,20,700,7.0,42.0,840.0
5,Webcam,Accessories,95,6,570,19.0,114.0,684.0

In [44]:
#Here we find products which price is more then 50 but less then 150
mid_price_products = df[
    (df["price"] >= 50) &
    (df["price"] <=150)
]

mid_price_products

,product,category,price,quantity,revenue,tax,price_with_tax,revenue_with_tax
2,Keyboard,Accessories,75,10,750,15.0,90.0,900.0
4,Headphones,Audio,120,8,960,24.0,144.0,1152.0
5,Webcam,Accessories,95,6,570,19.0,114.0,684.0