In [2]:
import pandas as pd

sales = pd.DataFrame({
    "product": ["Book", "Pen", "Notebook"],
    "quantity": [3, 8, 5],
    "price": [12, 2, 6]
}, index = [10, 20, 30])
sales

     product  quantity  price
10      Book         3     12
20       Pen         8      2
30  Notebook         5      6

In [3]:
sales.iloc[1]

product     Pen
quantity      8
price         2
Name: 20, dtype: object

In [5]:
sales.loc[30]

product     Notebook
quantity           5
price              6
Name: 30, dtype: object

In [7]:
sales.loc[sales["product"] == "Pen"]

   product  quantity  price
20     Pen         8      2

In [8]:
sales

     product  quantity  price
10      Book         3     12
20       Pen         8      2
30  Notebook         5      6

In [9]:
sales.loc[sales["product"] == "Notebook"]

     product  quantity  price
30  Notebook         5      6

In [10]:
sales.loc[sales["quantity"] > 4]

     product  quantity  price
20       Pen         8      2
30  Notebook         5      6

In [18]:
sales["price"].max()
sales["price"].idxmax()

np.int64(10)

In [22]:
pd = sales.loc[sales.idxmax()]
pd

   product  quantity  price
20     Pen         8      2
20     Pen         8      2
10    Book         3     12

In [24]:
sales["price"].max()

np.int64(12)

In [27]:
sales.loc[sales["price"].idxmax()]

product     Book
quantity       3
price         12
Name: 10, dtype: object

In [ ]:
sales.loc[sales["quantity"].min()]

     product  quantity  price
10      Book         3     12
20       Pen         8      2
30  Notebook         5      6

In [34]:
sales["quantity"].min()

np.int64(3)

In [35]:
sales["quantity"].idxmin()

np.int64(10)

In [36]:
sales.loc[sales["quantity"].idxmin()]

product     Book
quantity       3
price         12
Name: 10, dtype: object

In [37]:
sales.loc[sales["price"].idxmin()]

product     Pen
quantity      8
price         2
Name: 20, dtype: object

In [40]:
sales.loc[20, "product"]

'Pen'

In [41]:
sales

     product  quantity  price
10      Book         3     12
20       Pen         8      2
30  Notebook         5      6

In [42]:
sales.loc[sales["quantity"].idxmax(), "product"]

'Pen'

In [43]:
sales["quantity"].sum()   # total quantity
sales["quantity"].mean()  # average quantity

np.float64(5.333333333333333)

In [45]:
a = sales["quantity"].sum()
print(a)

16

In [47]:
b = sales["price"].mean()
print(round(b, 2), "eur")

6.67 eur

In [48]:
sales["revenue"] = sales["price"] * sales["quantity"]
sales

     product  quantity  price  revenue
10      Book         3     12       36
20       Pen         8      2       16
30  Notebook         5      6       30

In [49]:
total_revenue = sales["revenue"].sum()
print("The total revenue:", total_revenue)

The total revenue: 82

In [50]:
sales.loc[sales["revenue"].idxmax(), "product"]

'Book'

In [51]:
sales[sales["revenue"] > 20]

     product  quantity  price  revenue
10      Book         3     12       36
30  Notebook         5      6       30

In [52]:
sales

     product  quantity  price  revenue
10      Book         3     12       36
20       Pen         8      2       16
30  Notebook         5      6       30

In [54]:
def classify_revenue(value):
    if value >= 30:
        return "High"
    else:
        return "Low"

sales["category"] = sales["revenue"].apply(classify_revenue)
sales

     product  quantity  price  revenue category
10      Book         3     12       36     High
20       Pen         8      2       16      Low
30  Notebook         5      6       30     High

In [58]:
def classify_revenue(value):
    if value > 35:
        return "High"
    elif value > 20 & value < 35:
        return "Medium"
    else:
        return "Low"
sales["category"] = sales["revenue"].apply(classify_revenue)
sales

     product  quantity  price  revenue category
10      Book         3     12       36     High
20       Pen         8      2       16      Low
30  Notebook         5      6       30   Medium

In [61]:
def classify_revenue(value):
    if value >= 35:
        return "High"
    elif value >= 20:
        return "Medium"
    else:
        return "Low"
def classify_order(value):
    if value >= 6:
        return "Large"
    else:
        return "Small"
sales["category"] = sales["revenue"].apply(classify_revenue)
sales["order_size"] = sales["quantity"].apply(classify_order)
sales

     product  quantity  price  revenue category order_size
10      Book         3     12       36     High      Small
20       Pen         8      2       16      Low      Large
30  Notebook         5      6       30   Medium      Small

In [66]:
sales.loc[sales["order_size"] == "Small"]

     product  quantity  price  revenue category order_size
10      Book         3     12       36     High      Small
30  Notebook         5      6       30   Medium      Small

In [67]:
small_sale = sales.loc[sales["order_size"] == "Small"]
total_revenue_s = small_sale["revenue"].sum()
print(total_revenue_s)

66

In [68]:
small_sale.loc[small_sale["revenue"].idxmax(), "product"]

'Book'