In [1]:
import pandas as pd

In [2]:
sales = pd.DataFrame({
    "product": ["Backpack", "Pen", "Notebook", "Lamp"],
    "category": ["Accessories", "Stationery", "Stationery", "Home"],
    "price": [40, 2, 8, 25],
    "quantity": [2, 30, 10, 3]
}, index=[10, 20, 30, 40])

sales

     product     category  price  quantity
10  Backpack  Accessories     40         2
20       Pen   Stationery      2        30
30  Notebook   Stationery      8        10
40      Lamp         Home     25         3

In [3]:
sales["revenue"] = sales["price"] * sales["quantity"]
sales

     product     category  price  quantity  revenue
10  Backpack  Accessories     40         2       80
20       Pen   Stationery      2        30       60
30  Notebook   Stationery      8        10       80
40      Lamp         Home     25         3       75

In [4]:
sales.loc[sales["price"].idxmax(), "product"]

'Backpack'

In [5]:
sales.loc[sales["revenue"].idxmax(), "product"]

'Backpack'

In [6]:
sales.loc[sales["revenue"] == sales["revenue"].max(), "product"]

10    Backpack
30    Notebook
Name: product, dtype: str

In [9]:
stationery = sales.loc[sales["category"] == "Stationery"]
stationery

     product    category  price  quantity  revenue
20       Pen  Stationery      2        30       60
30  Notebook  Stationery      8        10       80

In [12]:
stationery["revenue"].sum()

np.int64(140)

In [14]:
stationery.loc[stationery["price"].idxmax(), "product"]

'Notebook'

In [15]:
sales.sort_values("revenue", ascending=False)
sales

     product     category  price  quantity  revenue
10  Backpack  Accessories     40         2       80
20       Pen   Stationery      2        30       60
30  Notebook   Stationery      8        10       80
40      Lamp         Home     25         3       75

In [16]:
sales.sort_values("revenue", ascending=False)

     product     category  price  quantity  revenue
10  Backpack  Accessories     40         2       80
30  Notebook   Stationery      8        10       80
40      Lamp         Home     25         3       75
20       Pen   Stationery      2        30       60

In [17]:
sales.sort_values("revenue", ascending=True)

     product     category  price  quantity  revenue
20       Pen   Stationery      2        30       60
40      Lamp         Home     25         3       75
10  Backpack  Accessories     40         2       80
30  Notebook   Stationery      8        10       80

In [18]:
sales.sort_values("price", ascending=True).head(2)

     product    category  price  quantity  revenue
20       Pen  Stationery      2        30       60
30  Notebook  Stationery      8        10       80

In [21]:
sales.sort_values("quantity", ascending=False).head(2)

     product    category  price  quantity  revenue
20       Pen  Stationery      2        30       60
30  Notebook  Stationery      8        10       80

In [23]:
sales.sort_values("quantity", ascending=True)

     product     category  price  quantity  revenue
10  Backpack  Accessories     40         2       80
40      Lamp         Home     25         3       75
30  Notebook   Stationery      8        10       80
20       Pen   Stationery      2        30       60

In [31]:
sales.loc[sales["price"] >= 8].sort_values("revenue", ascending=False).head(2)

     product     category  price  quantity  revenue
10  Backpack  Accessories     40         2       80
30  Notebook   Stationery      8        10       80

In [32]:
sales.groupby("category")["revenue"].sum()

category
Accessories     80
Home            75
Stationery     140
Name: revenue, dtype: int64

In [33]:
sales.groupby("category")["quantity"].sum()

category
Accessories     2
Home            3
Stationery     40
Name: quantity, dtype: int64

In [35]:
sales.groupby("category")["revenue"].sum().sort_values(ascending=False)

category
Stationery     140
Accessories     80
Home            75
Name: revenue, dtype: int64

In [36]:
sales.groupby("category")["quantity"].sum().sort_values(ascending=False)

category
Stationery     40
Home            3
Accessories     2
Name: quantity, dtype: int64

In [37]:
sales.groupby("category")[["quantity", "revenue"]].sum()

             quantity  revenue
category
Accessories         2       80
Home                3       75
Stationery         40      140

In [40]:
sales.groupby("category")[["quantity", "revenue"]].idxmax()

             quantity  revenue
category
Accessories        10       10
Home               40       40
Stationery         20       30

In [44]:
category_summary = sales.groupby("category")[["quantity", "revenue"]].sum()

In [45]:
category_summary

             quantity  revenue
category
Accessories         2       80
Home                3       75
Stationery         40      140

In [46]:
category_summary.sort_values("revenue", ascending=False)

             quantity  revenue
category
Stationery         40      140
Accessories         2       80
Home                3       75

In [47]:
sales

     product     category  price  quantity  revenue
10  Backpack  Accessories     40         2       80
20       Pen   Stationery      2        30       60
30  Notebook   Stationery      8        10       80
40      Lamp         Home     25         3       75

In [52]:
sales.loc[sales["price"] >= 8].groupby("category")["revenue"].sum().sort_values(ascending=False)

category
Accessories    80
Stationery     80
Home           75
Name: revenue, dtype: int64

In [53]:
sales.groupby("category").agg(
    total_revenue=("revenue", "sum"),
    average_price=("price", "mean")
)

             total_revenue  average_price
category
Accessories             80           40.0
Home                    75           25.0
Stationery             140            5.0

In [57]:
sales.groupby("category").agg(
    total_revenue=("revenue", "sum"),
    average_price=("price", "mean"),
    total_quantity = ("quantity", "sum")
)

             total_revenue  average_price  total_quantity
category
Accessories             80           40.0               2
Home                    75           25.0               3
Stationery             140            5.0              40

In [58]:
summery = sales.groupby("category").agg(
    total_revenue=("revenue", "sum"),
    average_price=("price", "mean"),
    total_quantity = ("quantity", "sum")
)

In [61]:
summery.loc[summery["total_revenue"] >= 100]

            total_revenue  average_price  total_quantity
category
Stationery            140            5.0              40